export enum Colors {
    WHITE = "rgb(255, 255, 255)",
    DARK_GREEN = "rgb(8, 66, 3)",
    GREEN = "rgb(36, 193, 22)",
    SKY_BLUE = "rgb(156, 219, 233)",
    NIGHT_BLUE = "rgb(1, 18, 45)",
    OVERLAY_DARK = "rgba(0,0,0,0.5)",
    BLUE = "rgb(63, 175, 239)",
    ROCK_GRAY = "rgb(94, 92, 92)",
    DARK_GRAY = "rgb(43, 42, 42)",
    BLACK = "rgb(0, 0, 0)",
    SUNSET_GRASS = "rgb(255, 200, 150)",
    SUNSET_NIGHT = "rgb(100, 30, 0)",
    MINE_BROWN = "rgb(139, 69, 19)",
    MINE_NIGHT = "rgb(60, 30, 10)",
    MINE_PIPE = "rgb(160, 82, 45)",
    SKY_MOUNTAIN_DAY = "rgb(135, 206, 235)",
    SKY_MOUNTAIN_NIGHT = "rgb(25, 25, 112)",
    LUSH_GRASS = "rgb(34, 139, 34)",
    LUSH_NIGHT = "rgb(0, 50, 0)",
    ICY_CAVE_DAY = "rgb(176, 224, 230)",
    ICY_CAVE_NIGHT = "rgb(0, 51, 102)",
    ICY_PIPE = "rgb(173, 216, 230)",
    SNOWY_NIGHT = "rgb(220, 220, 220)",
    FROZEN_CASTLE_DAY = "rgb(169, 169, 169)",
    FROZEN_CASTLE_NIGHT = "rgb(40, 40, 40)",
    FROZEN_PIPE = "rgb(192, 192, 192)",
    AUTUMN_GRASS = "rgb(255, 165, 0)",
    AUTUMN_NIGHT = "rgb(139, 69, 19)",
    AUTUMN_PIPE = "rgb(255, 140, 0)",
    LAVA_CAVE_DAY = "rgb(178, 34, 34)",
    LAVA_CAVE_NIGHT = "rgb(70, 0, 0)",
    LAVA_PIPE = "rgb(255, 69, 0)",
    HIGH_SKY_DAY = "rgb(135, 206, 250)",
    HIGH_SKY_NIGHT = "rgb(0, 0, 128)"
}

export type LevelProperties = {
    bg_color: string,
    bg_night_color: string,
    pipe_color: string,
    pipe_width: number[],
    pipe_gap: number[],
    pipe_horizontal_gap: number[],
    is_topbottom_independent: boolean,
    has_top_pipe: boolean,
    has_bottom_pipe: boolean
};

export const LevelDesignMap: { [level_code: string]: LevelProperties } = {
    "W11": {
        bg_color: Colors.SKY_BLUE,
        bg_night_color: Colors.SKY_BLUE,
        pipe_color: Colors.GREEN,
        pipe_width: [50, 300],
        pipe_gap: [120, 180],
        pipe_horizontal_gap: [80, 200],
        is_topbottom_independent: true,
        has_top_pipe: false,
        has_bottom_pipe: true
    },
    "W12": {
        bg_color: Colors.NIGHT_BLUE,
        bg_night_color: Colors.NIGHT_BLUE,
        pipe_color: Colors.BLUE,
        pipe_width: [50, 200],
        pipe_gap: [140, 220],
        pipe_horizontal_gap: [80, 200],
        is_topbottom_independent: true,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W13": {
        bg_color: Colors.DARK_GREEN,
        bg_night_color: Colors.DARK_GREEN,
        pipe_color: Colors.GREEN,
        pipe_width: [50, 500],
        pipe_gap: [140, 240],
        pipe_horizontal_gap: [100, 200],
        is_topbottom_independent: true,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W14": {
        bg_color: Colors.DARK_GRAY,
        bg_night_color: Colors.DARK_GRAY,
        pipe_color: Colors.ROCK_GRAY,
        pipe_width: [50, 500],
        pipe_gap: [130, 200],
        pipe_horizontal_gap: [80, 200],
        is_topbottom_independent: true,
        has_top_pipe: false,
        has_bottom_pipe: true
    },
    "W21": {
        bg_color: Colors.SUNSET_GRASS,
        bg_night_color: Colors.SUNSET_NIGHT,
        pipe_color: Colors.GREEN,
        pipe_width: [60, 250],
        pipe_gap: [120, 180],
        pipe_horizontal_gap: [80, 180],
        is_topbottom_independent: false,
        has_top_pipe: false,
        has_bottom_pipe: true
    },
    "W22": {
        bg_color: Colors.MINE_BROWN,
        bg_night_color: Colors.MINE_NIGHT,
        pipe_color: Colors.MINE_PIPE,
        pipe_width: [40, 180],
        pipe_gap: [140, 220],
        pipe_horizontal_gap: [80, 150],
        is_topbottom_independent: true,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W23": {
        bg_color: Colors.SKY_MOUNTAIN_DAY,
        bg_night_color: Colors.SKY_MOUNTAIN_NIGHT,
        pipe_color: Colors.ROCK_GRAY,
        pipe_width: [50, 400],
        pipe_gap: [140, 240],
        pipe_horizontal_gap: [100, 200],
        is_topbottom_independent: true,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W24": {
        bg_color: Colors.DARK_GRAY,
        bg_night_color: Colors.BLACK,
        pipe_color: Colors.OVERLAY_DARK,
        pipe_width: [60, 500],
        pipe_gap: [130, 180],
        pipe_horizontal_gap: [80, 150],
        is_topbottom_independent: false,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W31": {
        bg_color: Colors.LUSH_GRASS,
        bg_night_color: Colors.LUSH_NIGHT,
        pipe_color: Colors.GREEN,
        pipe_width: [70, 300],
        pipe_gap: [130, 180],
        pipe_horizontal_gap: [70, 170],
        is_topbottom_independent: true,
        has_top_pipe: false,
        has_bottom_pipe: true
    },
    "W32": {
        bg_color: Colors.ICY_CAVE_DAY,
        bg_night_color: Colors.ICY_CAVE_NIGHT,
        pipe_color: Colors.ICY_PIPE,
        pipe_width: [30, 150],
        pipe_gap: [150, 230],
        pipe_horizontal_gap: [80, 180],
        is_topbottom_independent: true,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W33": {
        bg_color: Colors.WHITE,
        bg_night_color: Colors.SNOWY_NIGHT,
        pipe_color: Colors.ROCK_GRAY,
        pipe_width: [40, 350],
        pipe_gap: [150, 250],
        pipe_horizontal_gap: [100, 180],
        is_topbottom_independent: true,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W34": {
        bg_color: Colors.FROZEN_CASTLE_DAY,
        bg_night_color: Colors.FROZEN_CASTLE_NIGHT,
        pipe_color: Colors.FROZEN_PIPE,
        pipe_width: [50, 500],
        pipe_gap: [130, 180],
        pipe_horizontal_gap: [80, 140],
        is_topbottom_independent: false,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W41": {
        bg_color: Colors.AUTUMN_GRASS,
        bg_night_color: Colors.AUTUMN_NIGHT,
        pipe_color: Colors.AUTUMN_PIPE,
        pipe_width: [60, 280],
        pipe_gap: [130, 180],
        pipe_horizontal_gap: [80, 180],
        is_topbottom_independent: true,
        has_top_pipe: false,
        has_bottom_pipe: true
    },
    "W42": {
        bg_color: Colors.LAVA_CAVE_DAY,
        bg_night_color: Colors.LAVA_CAVE_NIGHT,
        pipe_color: Colors.LAVA_PIPE,
        pipe_width: [40, 200],
        pipe_gap: [140, 200],
        pipe_horizontal_gap: [80, 150],
        is_topbottom_independent: true,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W43": {
        bg_color: Colors.HIGH_SKY_DAY,
        bg_night_color: Colors.HIGH_SKY_NIGHT,
        pipe_color: Colors.WHITE,
        pipe_width: [30, 200],
        pipe_gap: [160, 300],
        pipe_horizontal_gap: [120, 220],
        is_topbottom_independent: true,
        has_top_pipe: true,
        has_bottom_pipe: true
    },
    "W44": {
        bg_color: Colors.BLACK,
        bg_night_color: Colors.BLACK,
        pipe_color: Colors.OVERLAY_DARK,
        pipe_width: [60, 500],
        pipe_gap: [120, 160],
        pipe_horizontal_gap: [80, 140],
        is_topbottom_independent: false,
        has_top_pipe: true,
        has_bottom_pipe: true
    }
};
